### ISSUE TITLE
Build failed on MacOS

### ISSUE THREAD

**Issue by ccellado** [jstkdng/ueberzugpp#141] opened 2023-10-06 17:31 UTC
MacOS: Sonoma
MBP 14 M1

```
❯ : brew install jstkdng/programs/ueberzugpp
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################################################################################## 100.0%
==> Fetching jstkdng/programs/ueberzugpp
==> Downloading https://github.com/jstkdng/ueberzugpp/archive/refs/tags/v2.9.2.tar.gz
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/566a0abbb795bd10395e15125a8bc8cb83863a6083a9adf5368331b99375a696--ueberzugpp-2.9.2.tar.gz
==> Installing ueberzugpp from jstkdng/programs
==> cmake -S . -B build -DENABLE_X11=false -DENABLE_WAYLAND=false -DENABLE_OPENCV=OFF
Last 15 lines from /Users/username/Library/Logs/Homebrew/ueberzugpp/01.cmake:
  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done (0.0s)
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING


CMake Generate step failed.  Build files cannot be regenerated correctly.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/jstkdng/homebrew-programs/issues

```

**Comment by jstkdng** [comment] 2023-10-07 16:13
hey, I have not tested sonoma so I don't know if `ueberzugpp` will work as is. You'll have to wait.

**Comment by jstkdng** [comment] 2024-02-02 04:37
ok, finally managed to build my own hackintosh and tested sonoma 14.3 and it builds fine. I'll update the homebrew package but that's the most I can do since I can't reproduce the issue. Closing

**Closed by jstkdng** 2024-02-02 04:37 UTC
