### ISSUE TITLE
Wrong scaling and position of previews in nnn preview-tui on Hyprland (Wayland)

### ISSUE THREAD

**Issue by ih8d8** [jstkdng/ueberzugpp#113] opened 2023-08-15 02:08 UTC
I use alacritty+tmux+nnn preview-tui+ueberzugpp. On my 4K monitor, I use a fractional scaling factor of 1.5 but even when I set it to 1, the issue doesn't go away.

cat /tmp/ueberzugpp-$USER.log
```
 _    _      _
| |  | |    | |                                _     _
| |  | | ___| |__   ___ _ __ _____   _  __ _ _| |_ _| |_
| |  | |/ _ \ '_ \ / _ \ '__|_  / | | |/ _` |_   _|_   _|
| |__| |  __/ |_) |  __/ |   / /| |_| | (_| | |_|   |_|
 \____/ \___|_.__/ \___|_|  /___|\__,_|\__, |
                                        __/ |
                                       |___/     v2.9.0
[2023-08-14 21:04:07.354] [terminal] [info] TERM="tmux-256color", TERM_PROGRAM="tmux"
[2023-08-14 21:04:07.364] [terminal] [info] PTY = /dev/pts/0
[2023-08-14 21:04:07.364] [wayland] [info] Using hyprland socket /tmp/hypr/9654749244117f7f150c6f2a2ce4dede6e8cbb25_1692057986/.socket.sock
[2023-08-14 21:04:07.385] [wayland] [info] Using hyprland socket /tmp/hypr/9654749244117f7f150c6f2a2ce4dede6e8cbb25_1692057986/.socket.sock
[2023-08-14 21:04:07.386] [wayland] [info] Canvas created
[2023-08-14 21:04:07.442] [main] [info] Listening for commands on socket /tmp/ueberzugpp-241089.socket
[2023-08-14 21:04:09.245] [main] [info] Command received: {"action":"remove","identifier":"nnn_ueberzug"}
[2023-08-14 21:04:09.673] [main] [info] Command received: {"action":"remove","identifier":"nnn_ueberzug"}
[2023-08-14 21:04:10.192] [main] [info] Command received: {"action":"remove","identifier":"nnn_ueberzug"}
[2023-08-14 21:04:11.128] [main] [info] Command received: {"action":"remove","identifier":"nnn_ueberzug"}
[2023-08-14 21:04:11.329] [main] [info] Command received: {"action":"remove","identifier":"nnn_ueberzug"}
[2023-08-14 21:04:12.504] [main] [info] Command received: {"action":"remove","identifier":"nnn_ueberzug"}
[2023-08-14 21:04:12.533] [main] [info] Command received: {"action":"add","height":"73","identifier":"nnn_ueberzug","path":"/home/test/Pictures/.wallpaper.jpg","scaler":"fit_contain","width":"135","x":0,"y":0}
[2023-08-14 21:04:12.576] [opencv] [info] Loading image /home/test/.cache/ueberzugpp/5cab63244b0825f7a386ef8fea1881a57d51e7f8e57df8dfbfea1aa3d408e60862d02ba98e955f84f73ed777e6f1c69285a724e775d25b3843292f9eb0774bdf.jpg
[2023-08-14 21:04:14.128] [main] [error] SIGTERM received, exiting.
```

![test](https://github.com/jstkdng/ueberzugpp/assets/45679035/9b6a022c-43f4-4522-ae73-5a1a0295feab)

**Comment by jstkdng** [comment] 2023-08-15 05:09
does this happen outside of tmux?

**Comment by ih8d8** [comment] 2023-08-15 05:33
I just installed `kitty` and tested `nnn` on it. It shows the previews without any issues in the right position and scale. So it's probably only related to `tmux`?

**Comment by jstkdng** [comment] 2023-08-15 12:58
Are you using `kitty` with the wayland backend?

**Comment by ih8d8** [comment] 2023-08-15 22:37
I'm on Hyprland. I checked with the command `hyprctl clients` and under `kitty` window it is said xwayland is disabled. I think this means it's on Wayland backend.

**Comment by jstkdng** [comment] 2023-08-16 20:58
I meant if you were using `ueberzugpp`'s `wayland` backend with `nnn`

**Comment by ih8d8** [comment] 2023-08-17 01:59
I'm not sure how to set it in `nnn.` I found `ueberzugg` in `preview-tui`, and added `-o wayland`, but the issue didn't go away.

**Comment by jstkdng** [comment] 2023-08-19 05:06
>It shows the previews without any issues in the right position and scale

you said this

>but the issue didn't go away.

but now you are saying this

I need some clarification, is it working completely, only in some cases or not at all?

**Comment by ih8d8** [comment] 2023-08-20 01:27
`preview-tui` is working as expected when using it with `kitty` but when using it with `tmux`, I encounter the aforementioned problem.

**Comment by ih8d8** [comment] 2023-08-21 16:45
I tested on another laptop that was not connected to any external monitor. The laptop's resolution was 1920x1080 and the scaling factor was set to 1. On that machine, there was no problem with tmux+nnn.

**Comment by jstkdng** [comment] 2023-08-21 20:59
I see, so the issue is with tmux + 4K monitor. Now that's a hard to debug issue since I don't have a 4k monitor.

**Comment by jstkdng** [comment] 2023-09-13 03:41
closing in favor of #122

**Closed by jstkdng** 2023-09-13 03:41 UTC
